---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
      - name: Build requirements.txt
        id: pip-compile
      - name: Build requirements-dev.txt
        id: pip-compile
        args: [requirements-dev.in]
      - name: Build mkdocs requirements.txt
        id: pip-compile
        args: [docs/requirements.txt]

  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
        files: requirements

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore-decorators=overrides
        exclude: tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - pydantic
        exclude: tests
