# --------- Pytest -------------

[tool.pytest.ini_options]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
filterwarnings = "ignore::DeprecationWarning"

# --------- Commitizen -------------

[tool.commitizen]
name = "cz_conventional_commits"
version = "5.1.0"
tag_format = "$version"
version_files = ["setup.py", "now8_api/entrypoints/api/main.py"]

# --------- Black -------------

[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'

# --------- pydocstyle -------------

[tool.pydocstyle]
convention = "google"
match = "^(now8_api)"
ignore_decorators = "^(overrides|api.get|router.get)"

# --------- mypy -------------

[tool.mypy]
plugins = ["pydantic.mypy"]
ignore_missing_imports = true
strict_optional = false
