# --------- Pytest -------------

[tool.pytest.ini_options]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
filterwarnings = "ignore::DeprecationWarning"
env = [
    "MADRID_DB_NAME={TEST_DB_NAME}",
    "MADRID_DB_USER={TEST_DB_USER}",
    "MADRID_DB_PASS={TEST_DB_PASS}",
    "MADRID_DB_HOST={TEST_DB_HOST}",
    "MADRID_DB_PORT={TEST_DB_PORT}",]

# --------- Commitizen -------------

[tool.commitizen]
name = "cz_conventional_commits"
version = "2.3.0"
tag_format = "$version"
version_files = ["setup.py",]

# --------- Black -------------

[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'

# --------- pydocstyle -------------

[tool.pydocstyle]
convention = "google"
match = "^(now8_api)"
ignore_decorators = "^(overrides|api.get|router.get)"

# --------- mypy -------------

[tool.mypy]
plugins = ["pydantic.mypy"]
ignore_missing_imports = true
strict_optional = false
