---
site_name: now8-api documentation
site_url: https://now8-org.github.io/now8-api/
repo_name: now8-org/now8-api
repo_url: http://github.com/now8-org/now8-api/

plugins:
  - search
  - autolinks
  - gen-files:
      scripts:
        - docs/generate_reference.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters:
          rendering:
            show_source: true
      watch:
        - ./now8_api
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
