---
name: Code checks

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests with pytest
        run: python -m pytest
