---
name: Code checks

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests with pytest
        run: python -m pytest
        env:
          DB_NAME: postgres
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASS: postgres
          DB_PORT: 5432
