---
name: Update dependencies

on:
  schedule:
    - cron: 34 3 * * 1

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          depth: 0
          submodules: true
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Update dependencies
        run: pip install pip-tools && pip-compile requirements-dev.in
      - name: Install dependencies
        run: pip install -r requirements.in
      - name: Run tests with pytest
        run: python -m pytest
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git diff-index --quiet HEAD \
            || git commit -m "build: update python dependencies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }})
